package com.arrive.terminal.core.model

object Constants {
    const val LOGIN_DRIVER_TITLE = "login_driver_title"
    const val LOGIN_ENTER_DRIVER_ID = "login_enter_driver_id"
    const val LOGIN_TO_DRIVER_ACTION = "login_to_driver_action"
    const val ACCOUNT_LOGIN_TITLE = "account_login_title"
    const val DRIVER_TITLE = "driver_title"
    const val DRIVER_MY_ACCOUNT = "driver_my_account"
    const val RIDES_CONFIRM_YOUR_RIDE = "rides_confirm_your_ride"
    const val RIDES_ITEM_DIFFERENT_RIDE = "rides_item_different_ride"
    const val ACCOUNT_ADD_NEW = "account_add_new"
    const val ACCOUNT_ARRIVE_MILES = "account_arrive_miles"
    const val ACCOUNT_ARRIVE_WALLET = "account_arrive_wallet"
    const val ACCOUNT_BALANCE = "account_balance"
    const val ACCOUNT_CREDIT = "account_credit"
    const val ACCOUNT_NUMBER_HINT = "account_number_hint"
    const val ACCOUNT_NUMBER_PIN = "account_number_pin"
    const val ACCOUNT_PAYMENT = "account_payment"
    const val ACCOUNT_REFILL_ACCOUNT = "account_refill_account"
    const val ACCOUNT_BACK = "account_back"
    const val ACCOUNT_CONFIRM_PAYMENT = "account_confirm_payment"
    const val ACCOUNT_PRICE_OTHER = "account_price_other"
    const val PAYMENT_METHOD_SHOW_BREAKDOWN = "payment_method_show_breakdown"
    const val PAYMENT_METHOD_TOTAL = "payment_method_total"
    const val PAYMENT_METHOD_FEES = "payment_method_fees"
    const val PAYMENT_METHOD_PAY_WITH_CARD = "payment_method_pay_with_card"
    const val PAYMENT_RESULT_POWERED_BY = "payment_result_powered_by"
    const val ENTER_CARD_TAP_OR_INSERT = "enter_card_tap_or_insert"
    const val PAYMENT_RESULT_RATE_TITLE = "payment_result_rate_title"
    const val NO_PRICE_SET_TITLE = "no_price_set_title"
    const val NO_RICE_MESSAGE = "no_rice_message"
    const val NO_PRICE_ACTION = "no_price_action"
    const val COMMON_CANCEL = "common_cancel"
    const val COMMON_HINT_ACCOUNT_NUMBER = "common_hint_account_number"
    const val COMMON_HINT_PIN = "common_hint_pin"
    const val COMMON_HINT_CREDIT_CARD = "common_hint_credit_card"
    const val COMMON_HINT_CARD_EXP = "common_hint_card_exp"
    const val COMMON_HINT_CVC = "common_hint_cvc"
    const val COMMON_TRY_AGAIN = "common_try_again"
    const val ITEM_CARD_DEFAULT = "item_card_default"
}
